# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spectral_line_broadening',
                'doc_host': 'https://Rhys-McAlister.github.io',
                'git_url': 'https://github.com/Rhys-McAlister/spectral_line_broadening',
                'lib_path': 'spectral_line_broadening'},
  'syms': {'spectral_line_broadening.core': {'spectral_line_broadening.core.foo': ('core.html#foo', 'spectral_line_broadening/core.py')}}}
